# Generated by Django 2.2.4 on 2019-08-21 09:05

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0032_auto_20190820_0957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentpresence',
            name='Attendance_Date',
            field=models.DateField(default=datetime.datetime(2019, 8, 21, 9, 5, 14, 437305, tzinfo=utc)),
        ),
    ]
